# Copyright 2025 Advance Insight
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
{
    "name": "AgriOS Trade",
    "summary": "Manage trade with farmers",
    "author": "Advance Insight",
    "website": "https://agrios.org",
    "category": "AgriOS",
    "version": "18.0.1.0.2",
    "license": "AGPL-3",
    "depends": [
        # Odoo Modules
        "account",
        "sale_management",
        "purchase",
        "stock",
        # OCA Modules
        "account_usability",
        # Agrios Modules
        "agrios_plot",
    ],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "security/ir_rule.xml",
        "data/ir_sequence_data.xml",
        "data/ir_cron_data.xml",
        "wizard/multiple_confirm_draft_contracts_wizard.xml",
        "wizard/multiple_set_contracted_mapped_qty_wizard.xml",
        "wizard/bulk_contract_action_wizard.xml",
        "wizard/account_payment_register_views.xml",
        "views/farmer_group_views.xml",
        "views/season_views.xml",
        "views/product_product_views.xml",
        "views/contract_views.xml",
        "views/res_partner_views.xml",
        "views/purchase_order_views.xml",
        "views/sale_order_views.xml",
        "views/ir_actions_act_window.xml",
        "views/res_config_settings_views.xml",
        "views/reports.xml",
        "views/account_journal.xml",
        "views/account_move.xml",
        "views/ir_ui_menu.xml",
    ],
    "demo": [
        "demo/res_currency_demo.xml",
        "demo/account_tax_group_demo.xml",
        "demo/account_tax_demo.xml",
        "demo/account_account_demo.xml",
        "demo/account_journal_demo.xml",
        "demo/season_demo.xml",
        "demo/product_category_demo.xml",
        "demo/product_product_demo.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
}
